# This dockerfile is used to easily setup the postgresql database for development and testing.

FROM postgres:latest

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB voicemail
COPY sql/create_tables.sql /docker-entrypoint-initdb.d/
